language: java

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq sun-javadb-client sun-javadb-core 
 
before_script:
 - pwd 
 - export PATH=$PATH:/usr/share/javadb/bin/
 - export DERBY_HOME=/usr/share/javadb
 - ij '~/dofi/src/main/resources/create_db.sql'
 - cat ~/dofi/src/main/resources/create_db.sql