package pl.com.setvar.dofi.dao;
// Generated Sep 9, 2013 9:02:24 PM by Hibernate Tools 3.2.1.GA



/**
 * Juxtapositions generated by hbm2java
 */
public class Juxtapositions  implements java.io.Serializable {


     private int id;
     private int tag;
     private String name;

    public Juxtapositions() {
    }

    public Juxtapositions(int id, int tag, String name) {
       this.id = id;
       this.tag = tag;
       this.name = name;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getTag() {
        return this.tag;
    }
    
    public void setTag(int tag) {
        this.tag = tag;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


