package pl.com.setvar.dofi.dao;
// Generated Sep 9, 2013 9:02:24 PM by Hibernate Tools 3.2.1.GA



/**
 * OperationTags generated by hbm2java
 */
public class OperationTags  implements java.io.Serializable {


     private int id;
     private int tag;
     private int operation;

    public OperationTags() {
    }

    public OperationTags(int id, int tag, int operation) {
       this.id = id;
       this.tag = tag;
       this.operation = operation;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getTag() {
        return this.tag;
    }
    
    public void setTag(int tag) {
        this.tag = tag;
    }
    public int getOperation() {
        return this.operation;
    }
    
    public void setOperation(int operation) {
        this.operation = operation;
    }




}


