package pl.com.setvar.dofi.dao;
// Generated Sep 9, 2013 9:02:24 PM by Hibernate Tools 3.2.1.GA



/**
 * Taglinks generated by hbm2java
 */
public class Taglinks  implements java.io.Serializable {


     private int id;
     private String word;
     private int tag;

    public Taglinks() {
    }

    public Taglinks(int id, String word, int tag) {
       this.id = id;
       this.word = word;
       this.tag = tag;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getWord() {
        return this.word;
    }
    
    public void setWord(String word) {
        this.word = word;
    }
    public int getTag() {
        return this.tag;
    }
    
    public void setTag(int tag) {
        this.tag = tag;
    }




}


